### ISSUE TITLE
`--title` flag doesn't seem to select the correct 1Password item

### ISSUE THREAD

**Issue by bachya** [apiology/op-env#79]
* op-env version: 0.9.0
* Python version: 3.9.9
* Operating System: macOS 12.1

### Description

I am attempting to pursue a model whereby I use the same tag name in various 1Password items (for example, using `OP_ENV_CREDENTIAL` for the credential field within an API Credential item). It's my understanding that the `--title` flag allows one to specify the 1Password item from which values should be retrieved; however, I am consistently receiving a `TooManyEntriesOPLookupError` exception.

### What I Did

I created two API Credential items in 1Password and attached the `OP_ENV_CREDENTIAL` tag to both:

![CleanShot 2022-01-10 at 17 01 53](https://user-images.githubusercontent.com/47216/148858220-ce254edf-8a91-462a-9cbe-70a4df3677e5.png)

![CleanShot 2022-01-10 at 17 01 45](https://user-images.githubusercontent.com/47216/148858223-e5c076c3-a0a0-4a4c-aeca-150b431b6735.png)

I ran this command:

```
op-env json --title "Linode API Token: Terraform" -e OP_ENV_CREDENTIAL
```

...and received this stacktrace:

```
Traceback (most recent call last):
  File "/usr/local/bin/op-env", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/op_env/_cli.py", line 142, in main
    return process_args(args)
  File "/usr/local/lib/python3.9/site-packages/op_env/_cli.py", line 127, in process_args
    new_env = do_lookups(args['environment'], args['title'])
  File "/usr/local/lib/python3.9/site-packages/op_env/op.py", line 273, in do_lookups
    env_lookups = _do_env_lookups(env_var_names)
  File "/usr/local/lib/python3.9/site-packages/op_env/op.py", line 251, in _do_env_lookups
    list_items_output = _op_list_items(env_var_names)
  File "/usr/local/lib/python3.9/site-packages/op_env/op.py", line 98, in _op_list_items
    raise TooManyEntriesOPLookupError("Too many 1Password entries "
op_env.op.TooManyEntriesOPLookupError: Too many 1Password entries with tag OP_ENV_CREDENTIAL found
```

Am I misunderstanding what the `--title` flag is supposed to do?

**Comment by apiology** [comment]
If you use `--title`, you can drop `-e` - the idea of `--title` is that every single tagged name on the item is used.  Let me know if that doesn't help, or if the general option set isn't super helpful for your need.  I could potentially see the use for the type of narrowing option you describe (also for a lot of other ways of doing a query here--just a matter of choosing and trying not to make things too confusing).
